### ISSUE TITLE
make clojurescript dep optional

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/rcf#25]
danieljomphe RCF: Have you tried making it possible to exclude the CLJS dep in our CLJ-only projects?
I've seen 3 categories of our isometric deps:
Those for which we exclude CLJS and they break (RCF).
Those for which we exclude CLJS and they still work (clout, :scope provided).
Those who don't bring in CLJS automatically (scope-capture, profile-based).

https://github.com/weavejester/clout/blob/master/project.clj
https://github.com/vvvvalvalval/scope-capture/blob/master/project.clj

**Comment by Cyrik** [comment]
Since this is deps.edn based :scope does not work well for transitive stuff, so alias/profile would be the way to go

**Comment by delyada** [comment]
Hi Dustin & team!

Better late feedback than never:

I finally upgraded our RCF dep and it no more pulls in cljs (nor transitively guava, nor findbugs).

This is very great, thanks a lot for this change!

Here's what we could do due to this in our deps.edn:

![image](https://user-images.githubusercontent.com/70277581/153951386-0568da23-e3db-4f4c-9e1a-7eb4faea0f12.png)
